### ISSUE TITLE
"Allow Motion" Popup keeps re-appearing 

### ISSUE THREAD

**Issue by ikifar2012** [home-assistant/home-assistant-iOS#177] opened 2018-12-09 03:08 UTC
Version 1.5.0 (31)
Every time I start the iOS app since the beginning of the beta I have been getting this Allow Motion popup. I do not use any location features of the Home Assistant app so I have everything disabled. But when I click deny in this popup it does not seem to save my choice after restarting the app
![image](https://user-images.githubusercontent.com/20800434/49692992-9c5d5180-fb35-11e8-88a6-820734927ef7.png)

**Comment by Bojan023** [comment] 2019-01-15 19:31
I can confirm same issue. Latest iOS and Companion version.

**Comment by Bojan023** [comment] 2019-01-17 10:12
This indeed solved the problem, thanks! Maybe it should be included somewhere? FAQ/readme?

Op 17 jan. 2019 om 03:25 heeft towerhand <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


I had this problem on my wife’s phone, it was due to bad settings on the iPhone and not due to the home assistant app.

To fix this go to your settings, privacy, motion and fitness, and turn on “fitness tracking”, next time you open the app a pop up should show up and select to turn on motion.

I think this issue could be closed.

**Comment by h4nc** [comment] 2019-01-17 10:22
I think this setting is global, so if you turn that off, you will turn it off for all apps.

**Comment by amelchio** [comment] 2019-01-17 10:43
My Home Assistant is not publicly accessible so I do not use the companion component. I want to disable all privacy permissions for the Home Assistant app since I cannot use those features anyway.

However, depending on what I allow, I get three different popups during each restart:
* Location
* Motion
* Notification

Only if I allow everything will I get rid of all the popups.

**Comment by h4nc** [comment] 2019-01-17 10:52
I have the global motion setting enabled and the popup still shows up.

I also have no homeassistant entry in that fitness motion list to en- or disable.

**Comment by Bojan023** [comment] 2019-01-17 11:09
If the global setting is enabled, also make sure the option to track (first option within the fitness setting) is enabled as well. The pop-up will appear for the last time when opening the companion app and if allowed this is the last one you’ll ever see! ;-)

**Comment by Bojan023** [comment] 2019-01-17 11:11
@amelcio

I suggest to accept everything and try if disabling every permission via the settings menu gets rid of all pop-ups.

**Comment by amelchio** [comment] 2019-01-17 11:31
@Bojan023 then the popups return, asking if I want to re-enable

**Comment by towerhand** [comment] 2019-01-17 12:42
“I had this problem on my wife’s phone, it was due to bad settings on the iPhone and not due to the home assistant app. 

To fix this go to your settings, privacy, motion and fitness, and turn on “fitness tracking”, next time you open the app a pop up should show up and select to turn on motion. “

This is the comment I removed because I noticed the issue in this ticket was about disabling the motion and not enabling. Hopefully it helps other people that have the same problem @bojan023 and I had.

**Comment by amelchio** [comment] 2019-01-17 12:50
Proposals that involve turning anything on are workarounds, not fixes.

**Comment by trimethia** [comment] 2019-01-23 13:44
Me too, same issue. Keep getting popups asking access to motion/location whenever I re-open the app after closing.

**Comment by h4nc** [comment] 2019-02-12 18:51
Anything new on this one, I still get those messages?

**Closed** 2019-02-14 01:13 UTC
Labels: location
