### ISSUE TITLE
Constantly getting "Connection lost. Reconnecting..."

### ISSUE THREAD

**Issue by alireza202** [home-assistant/home-assistant-iOS#201] opened 2019-01-22 23:27 UTC
Every time I open the app, I see the "Connection lost. Reconnecting..." on the bottom, and I suspect that causes the location reporting to not work. What could be the cause?

I'm running 0.85.1 on Pi3, and I have iPhone X with latest iOS version. I had this problem with previous versions of HA as well, and that's one of the reasons I gave up on HA before. I'm trying to see if I can make it work this time.

If it helps, I also constantly get errors in my HA log on "Updating ecobee weather took longer than..." every minute or more. Not sure if it is related.

**Comment by cmsimike** [comment] 2019-01-23 00:07
if you visit hass not using the ios app, does it behave similarly?
can you please explain a bit more about your setup? do you have hass punching through your firewall? proxying through nginx/some other server?

**Comment by alireza202** [comment] 2019-01-23 05:44
It only happens on the iOS app. I don't have firewall, and I'm not using nginx. I have Google Wifi as my router.

I'm disabling Ecobee to see if the problem persists.

**Comment by alireza202** [comment] 2019-01-23 22:39
Disabling Ecobee did not help. What could cause this issue?

**Comment by garyak** [comment] 2019-02-18 23:32
I also experience this behavior on my phone. iPhone8, iOS 12.1.4, HassOS 1.9, iOS App 1.5.  This happens both inside and outside my network. No proxy, Static IP, port-forwarded through my router.  Location displayed does not update until application is active. I also believe, and currently testing, that it blocks my arrival automation trigger. Automation has properly triggered when iOS application is open on my phone three consecutive times now. When in the background, the automation has failed to trigger. Just trying to narrow down the root cause.

**Comment by alireza202** [comment] 2019-02-18 23:42
FYI, I switched to ethernet connection, and although I still see this message, but it is much shorter; most of the time less than a second. It used to take over 5 or 10 seconds before.

**Comment by robbiet480** [comment] 2019-02-23 09:38
The connection lost message is entirely driven by the Home Assistant frontend, the iOS app doesn't have any control over it. Not sure why this would be happening to you, but I'd agree with @cmsimike's initial thoughts on what's your setup look like. The only other thing would be if your network is just a tad slow and you are bringing the app out of the background vs fresh so the background state needs to reconnect once foregrounded again. This is normal iOS behavior.

Feel free to keep using this issue but I'm going to close it until it appears it is directly related to the iOS app.

**Closed by robbiet480** 2019-02-23 09:38 UTC

**Comment by glassbase** [comment] 2019-03-27 14:08
I will comment this here in case others find it via Google like myself and are struggling with this issue... I had been getting this for the last few weeks. Was driving me insane. 

I found a OLD [issue](https://github.com/home-assistant/home-assistant/issues/4726) that mentions adding these two lines to your nginx location config:
```
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade"; 
```

Now my app reconnects within a second instead of not reconnecting at all without hitting refresh.

**Comment by robbiet480** [comment] 2019-03-28 02:59
@glassbase Mind linking that issue here, this has plagued a lot of users and I wanna see the history.

**Comment by glassbase** [comment] 2019-04-10 21:20
I hyperlinked it in my original comment. 

https://github.com/home-assistant/home-assistant/issues/4726

**Comment by arallsopp** [comment] 2021-07-22 22:07
I've also had the 'connection lost reconnecting' message on the iOS app constantly. I don't have any external access, so this is when I'm on the home wifi, able to load other urls, but not home assistant. 

Oddly, I also get it on Chrome from the same iOS device. Again, other sites load fine. Incognito windows or a different browser on my iOS device don't fix it. 

Yet opening a browser on my desktop shows the same urls (homeassistant.local:8123, and 10.13.1.239:8123) work fine. The iPhone just loses its ability to connect periodically.

Restarting the iPhone sometimes works. Just leaving it a while sometimes works. Force closing the app and relaunching rarely does anything. It feels like the websocket gets hung up somewhere in iOS and won't create another until its done its thing.

**Comment by dariodoc** [comment] 2023-03-29 16:15
Have you made sure that no other devices on your network get assigned the same IP addresses? That is another possible cause of losing connectivity. I had a wifi pir sensor that connected only for a few seconds to the network and it was getting the same IP address of my HA host pc. Just saying..
