### ISSUE TITLE
Can't press the 'Close' button on the 'For best experience'-screen (iPhone SE)

### ISSUE THREAD

**Issue by Alwik** [home-assistant/home-assistant-iOS#282] opened 2019-04-29 07:52 UTC
Both in portrait as in landscape mode, clocking 'Close' doesn't work.
Tried multiple times, force-closed etc.
All other buttons in the onboarding-flow work correct
Happend on both 2.0b42 as 2.0b43

**Comment by robbiet480** [comment] 2019-05-01 09:13
@Alwik Let me know if upcoming build 44 fixes your issues, thanks!

**Comment by christhehoff** [comment] 2019-05-01 12:02
Still and issue for me. This time it reset all the “Allow” options (which could then be selected) but still unable to hit the “Close” button.

**Comment by Alwik** [comment] 2019-05-01 18:55
Hi @robbiet480 , indeed, same problem as before (like christhehoff already mentioned)

**Comment by imuncas** [comment] 2019-05-01 19:49
I confirm, the issue is still there in 44.

**Comment by robbiet480** [comment] 2019-05-02 04:25
For sure fixed via 0122292d67a982a5a5188c4ffaac90411fcedc2a along with other iPhone SE issues.

**Closed by robbiet480** 2019-05-02 04:25 UTC
Labels: 2.0 Beta
