### ISSUE TITLE
[FR] Use other theme variable for iOS notchbar

### ISSUE THREAD

**Issue by dwainscheeren** [home-assistant/home-assistant-iOS#561] opened 2020-03-07 11:19 UTC
Hi,

I highly recommend to change the way you can color the iOS notchbar. It now can be colorized with using `primary-color`.

Only if I want a dark notchbar I need to set a dark color there, but then my whole HA theme uses that dark color for every primary-color.

Adding a option like `ios-notchbar-color` would be better.

Had this discussion with a lot of other users with the same problem, so please change it :)

**Comment by dwainscheeren** [comment] 2020-03-07 11:47
I see in the code it is set here https://github.com/home-assistant/home-assistant-iOS/blob/master/HomeAssistant/Views/WebViewController.swift#L639
There is also an option `app-header-background-color` which is loaded on top of that `headerKey` but it doesn't work. It only styles the main header not the notch bar.

**Comment by dwainscheeren** [comment] 2020-03-07 13:38
Also an option to change the `UIStatusBarStyle` from lightContent to .black would be great! https://github.com/home-assistant/home-assistant-iOS/blob/master/HomeAssistant/Views/WebViewController.swift#L400 To set the text black instead of always being white in the notch.

**Comment by TomBrien** [comment] 2020-03-08 11:16
This is a duplicate of #531 which has been implemented and will be in the next release. See that issue for description of the change

**Closed by TomBrien** 2020-03-08 11:16 UTC
Labels: duplicate

**Comment by Phontana** [comment] 2020-06-14 18:11
@TomBrien not exactly. Yes, the status bar color part is implemented in the latest (2020.1) release, but the option to set the status bar text color is not. I will create another issue for that, since this one is closed already.
