### ISSUE TITLE
Notifications for multiple devices using notify.notify not working.

### ISSUE THREAD

**Issue by talondnb** [home-assistant/home-assistant-iOS#427] opened 2019-08-16 04:51 UTC
iPhone 7 and 7 plus, 2.0b (62). Different users.

The notify.notify service only seems to work for my phone (7, admin user) and not my wife's 7plus. I've performed scorched earth resets on both phones and each time it seems to only work one at a time.

At one stage after moving to 2.0b on both phones, only the 7 plus was working. I did the full reset on both but again it only registers on one.

Each time I've tried to fix this issue, i've run through this for both phones:

https://companion.home-assistant.io/en/next/troubleshooting/beta-cleaning

Any ideas?

Only running mobile_app and not ios.

**Comment by TomBrien** [comment] 2019-08-16 06:13
That’s interesting can you confirm that you see `notify.mobile_app_<wife’s_device_ID>` in the developer tools>services drop down? Also, can you see what entities are listed under the integration for that phone in Configuration>Integrations>Mobile App.

**Comment by TomBrien** [comment] 2019-08-17 09:20
I’ve just tried to reproduce this on a clean install of the beta on a different phone signed in to a non-admin user and I cannot reproduce. Can you please post the automation or script that isn’t working for you.

**Comment by talondnb** [comment] 2019-08-21 10:45
Apologies for the delayed response.

Automation below, but goes for anything using notify.notify service. I'm also manually triggering the service with {"message": "test"} and the message only goes to one device and not all. Currently I got it working on my iphone7 but the iphone 7plus is not working, even after multiple scorched earth resets.

`### Notification Automation - Solar Generated
  - alias: 'Solar Energy Generated Today'
    trigger:
      - platform: sun
        event: sunset
        offset: "+00:15:00"
    action:
      - service: notify.notify
        data:
          message: 'Total solar energy generated today is {{ states.sensor.energy_generation.state }} kWh resulting in a Net Export Credit of {{ states.sensor.net_export.state }}.'
          title: Solar Energy Today`

**Comment by TomBrien** [comment] 2019-08-21 12:43
I think the `notify.notify` method for sending to all device is not supported for `mobile_app`. I think this may be a due to limited number of message attempts the server can run while being kept free.

I would suggest two separate `action:` entries, one for each device using `notify.mobile_app_<device_ID>` for the appropriate device. This should work then.

**Comment by TomBrien** [comment] 2019-10-14 20:40
Closing due to no further activity

**Closed** 2019-10-14 20:40 UTC
