### ISSUE TITLE
Battery level not updating on iPhone XS

### ISSUE THREAD

**Issue by artkrz** [home-assistant/home-assistant-iOS#556] opened 2020-03-02 09:22 UTC
Hi,

I'm running latest app on iPhone XS (13.4 latest public beta) and the battery level sensor isn't updating. It did initially when I installed the app but it never updated after that. The error I'm seeing in the logs is:

`Received invalid webhook payload: required key not provided @ data[11][‘state’]`

Location updates work fine though.

**Comment by Krocko** [comment] 2020-03-02 09:32
Please see #547

**Comment by TomBrien** [comment] 2020-03-02 10:13
Closing as duplicate of #547

**Closed by TomBrien** 2020-03-02 10:13 UTC
Labels: duplicate
