### ISSUE TITLE
Images no longer shown in notification (latest build)

### ISSUE THREAD

**Issue by Swiftnesses** [home-assistant/home-assistant-iOS#362] opened 2019-05-10 08:19 UTC
@robbiet480 Just testing some new flows in Node Red and I've noticed that push messages with image_url no longer show the image...

Example:

```
    image_url: "https://www.test.com.jpg",
    image_type: "jpg"
```

**Comment by robbiet480** [comment] 2019-05-10 08:28
@Swiftnesses That isn’t a valid URL, maybe that’s why?

**Comment by Swiftnesses** [comment] 2019-05-10 08:29
> @Swiftnesses That isn’t a valid URL, maybe that’s why?

@robbiet480 It was a terrible example, my actual URL is valid 👍

**Comment by TomBrien** [comment] 2019-05-10 08:57
@Swiftnesses can you post your full automation/script here, with an reactions you need to make for privacy?

**Comment by Swiftnesses** [comment] 2019-05-10 09:36
I use node red, but basically I'm passing this:

```
msg.ios_notification = 
{ 
    title: "Duck Coop - Door Opened", 
    message: "The door has been opened, please check the image.",
    image_url: "http://192.168.1.48:8090/webcam/a94df035fc91a158c1f9d7a1c769ca66/a94df035fc91a158c1f9d7a1c769ca66_raw.jpg",
    image_type: "jpg",
    target: "both"
};
```
This has worked until a recent build (not sure which!).

**Comment by Swiftnesses** [comment] 2019-05-10 09:40
Normal push notifications work fine, including push categories (buttons), it's the image display that's stopped working...

**Comment by TomBrien** [comment] 2019-05-10 09:58
I'm not hugely familiar (ok at all) with node red but are you possibly missing a value for `hide-thumbnail` anywhere or are this and category defined elsewhere?

**Comment by Swiftnesses** [comment] 2019-05-10 09:59
Hi @TomBrien this is optional and in my test, I don't pass it...

**Comment by TomBrien** [comment] 2019-05-10 10:04
Ok. I'm seeing that images behind a `https` url aren't working. Not sure if that's going to prove to be related

**Comment by Swiftnesses** [comment] 2019-05-10 10:19
I'm not entirely sure, but this worked flawlessly before, so something has changed, sadly, I'm not sure what...

The images are also coming via my local network and the grab time is in the milliseconds...

**Comment by vandalon** [comment] 2019-05-11 11:53
I can confirm image no longer working in notifications after build 55.
I've tested all builds after 55 from 58 downwards. (I upgraded from 54  to 58, then i noticed the pictures not working. I then tried 57and 56 and noticed the same issue. Then installed 55 and all was good again.

This is the json a insert into home assistant. 

```
{"message":"Ding Dong!","data":{"push":{"category":"camera","sound":{"critical":1,"name":"default"}},"entity_id":"camera.voordeur"}}
```

**Comment by TomBrien** [comment] 2019-05-11 16:26
In build 58 I still have 0 % delivery of `https` attachments and about 50 % with `http`

**Comment by rpcaeiro** [comment] 2019-05-18 22:25
Exactly the same issue here. Build 58 fails a lot. Version 1.5 never fails and the image is always in the notification.

**Comment by giuarb** [comment] 2019-05-21 10:50
Same here.....

**Comment by tinglis1** [comment] 2019-05-26 04:08
I think i am having the same issue.
I have one node-red automation that sends an image to my phone with the beta and it isn't getting the images. The same notification sent to another phone running the old app is getting the image.
my image is using the duckdns link but have also tried the nabu casa link with no change.

I have also tested with the example from the documentation without success either.
https://www.home-assistant.io/docs/ecosystem/ios/notifications/attachments/

**Comment by Swiftnesses** [comment] 2019-05-26 08:12
This is a killer, think for now I'm going to roll back to the old mobile build...

**Comment by vandalon** [comment] 2019-05-28 08:09
I can confirm this issue still exist in build 59

**Comment by giuarb** [comment] 2019-05-29 20:03
picture notification is one of the best features of the app, just installed version 60 and it doesn't look it is working but I will double check once home

**Comment by robbiet480** [comment] 2019-05-30 00:42
Working on this tonight.

**Comment by vandalon** [comment] 2019-05-30 06:11
You sir, are awesome

**Comment by giuarb** [comment] 2019-06-02 18:26
it may be more complicated than thought.
Which was the last working version for notification?

**Comment by vandalon** [comment] 2019-06-02 19:02
Build 55 works perfectly, 56 doesn't :)

**Comment by giuarb** [comment] 2019-06-06 00:15
I am back on the 55 and works like a charm! also my apple watch shows the picture

**Comment by mountainsandcode** [comment] 2019-06-11 12:59
Hi @robbiet480, what can we do to help on the debugging of this issue? 
I’ve tried a few different setups but haven’t concluded anything other than the fact that on https it almost never works, on http it’s hit and miss. 
Could it be some kind of timeout that the app runs into when trying to download the image?

**Comment by giuarb** [comment] 2019-06-13 22:51
I am also available for help
Still on 55 all works

**Comment by PDekker** [comment] 2019-06-16 09:17
Same here. Is it related to the stream component?

**Comment by giuarb** [comment] 2019-06-16 22:39
> Same here. Is it related to the stream component?

revert to 55, all works then.
This app should be a paid one like zone ninja for zoneminder, this would allow great people to work on it.
I wouldn't mind paying for it

**Comment by robbiet480** [comment] 2019-06-18 06:23
Fixed! Traced down to a memory leak in Realm, our database. Please let me know if I need to reopen after the next build which should be out in ~3 hours.

**Comment by tinglis1** [comment] 2019-06-18 07:36
@giuarb
You can support Robbie through Patreon
https://www.patreon.com/robbiet480/overview

**Comment by giuarb** [comment] 2019-06-19 01:46
> @giuarb
> You can support Robbie through Patreon
> https://www.patreon.com/robbiet480/overview

I will

**Comment by giuarb** [comment] 2019-06-19 01:47
Installed version 60 but notification isn't working at all (of course I did the import push.....)

**Comment by robbiet480** [comment] 2019-06-19 01:48
@giuarb Can you please share the payload you are sending?

**Comment by tinglis1** [comment] 2019-06-19 02:19
@giuarb isn’t the latest version 61?

**Comment by robbiet480** [comment] 2019-06-19 02:20
Oh good catch @tinglis1, yes, @giuarb, the latest version is 61.

**Comment by tinglis1** [comment] 2019-06-19 02:23
FYI, I have tested it and it is working for me with v61.

**Comment by giuarb** [comment] 2019-06-19 02:45
sorry it is the 61, I have removed the 55, installed the 61, ,enabled auth for notifications, import push
I don't get any notification at all.
I have installed from remote by entering the duckdns https url

**Comment by vandalon** [comment] 2019-06-19 07:18
For me the issues seems to be resolved with build 61. Great work Robbie!

**Comment by vandalon** [comment] 2019-06-19 08:21
I do notice that sometimes the picture that is shown in the banner is not always shown. I had this in build 55 as well. It does not happen often but sometimes and it seems random.

**Comment by vandalon** [comment] 2019-06-24 17:49
It seems that images are still not always sent in the 2.0 app, where as the same notification always gives an image on the 1.x version. (my girlfriend is still running the 1.x app). I can't say when it happens and when not. seems random.

**Comment by rpcaeiro** [comment] 2019-06-24 21:13
Exactly the same here as vandalon

**Comment by vandalon** [comment] 2019-07-05 17:36
I have about 50% succes rate :) (all notifications here should have images).

Maybe it's ok to re-open this issue?

![image](https://user-images.githubusercontent.com/3370317/60737712-0919bc80-9f5c-11e9-8a1f-7a645c15aea4.png)

**Comment by JohannPie** [comment] 2019-08-27 09:05
Build 62 and no Images for me

**Comment by vandalon** [comment] 2019-09-19 17:13
Since today it seems no image is getting trough and also camera live view no longer works. Both work perfectly in the old (1.5) app.

**Comment by TomBrien** [comment] 2019-09-19 17:29
This is a known bug that sneaked in with b63. Plan is to release a new build in the coming days.

**Comment by vandalon** [comment] 2019-09-30 10:14
> This is a known bug that sneaked in with b63. Plan is to release a new build in the coming days.

Any news on this by any chance ? :)

**Comment by vandalon** [comment] 2019-10-18 11:21
Since b67 everything seems ok again. But, it seems that since ios 13 (this could be coincidence) that notifications take way longer to arrive, about 30 seconds. This is usually not an issue but I also connected a doorbell to HA (via gpio) and 30 seconds before a notification is a bit long for a doorbell :)

**Comment by mountainsandcode** [comment] 2019-10-18 18:30
Indeed appears to be working fine - I don't have the issues with the delay however, they arrive pretty much instantly for me

**Comment by vandalon** [comment] 2019-10-18 18:47
It seems, with the app open , notifications are instant. With iphone unlocked as well, When locked the delay seems to appear.

**Comment by TomBrien** [comment] 2019-10-19 11:55
I just did some testing with latest build (b68) and notifications contains text only are almost instant (never more than 2 seconds delay), notifications with images can take a while longer I've certainly seen 30 seconds. Test scenario was phone locked without HA Companion App running in the background, so should be the worst case client side.

**Comment by vandalon** [comment] 2019-10-19 11:57
Awesome test. I can also say that with the 1.51 version of the app (the current one in the app store) my doorbell notifications are instant. (with image).

**Comment by TomBrien** [comment] 2019-10-19 11:59
2.0 uses a different service for notifications so that could be the root cause. Can you create a new issue for this delay please? I think this issue can be closed and I'd prefer it not to get confused.

**Closed by TomBrien** 2019-10-19 11:59 UTC
Labels: 2.0 Beta, notifications

**Comment by vandalon** [comment] 2019-10-19 12:02
#453

**Comment by lowrisk75** [comment] 2021-04-25 18:16
This stopped working from me since I have nginx installed, 
the snapshot work just fine, I can load the snapshot locally or manually but is not attached to my iOS notification.
My AppleWatch mention a notification but nothing on my iPhone.

node-red : 


```
{
   "title": "Car outside",
   "message": "There is a car outside",
   "data": {
       "subtitle": "Side motion detector",
       "push": {
           "sound": "Alarm_Nightstand_Haptic.caf"
        },
       "attachment": {
           "content-type": "jpg",
           "url": "https:mysub.domain.com/local/front_snapshot.jpg"
        }
    }
}
```
