### ISSUE TITLE
2.0 missing refresh button on home screen

### ISSUE THREAD

**Issue by burkemw3** [home-assistant/home-assistant-iOS#501] opened 2019-12-01 18:34 UTC
When I open the app, it doesn't always correctly find my hass server. In the old version, there was a refresh button on the login page.

When the app couldn't connect to the server the first time, it would show the login page. I could click refresh, then see my dashboard.

Now, I need to restart the app (Home screen double tap, swipe up on app, click on app in launcher) to get it to load the dashboard. This is more steps and more annoying.

**Comment by TomBrien** [comment] 2019-12-01 18:35
This is a known bug. You can pull down to refresh the view. This replaces the old refresh and manual location buttons

**Comment by TomBrien** [comment] 2019-12-01 18:37
Closing as duplicate of #426. Feel free to reopen if I have misunderstood.

**Closed by TomBrien** 2019-12-01 18:37 UTC
Labels: duplicate
