### ISSUE TITLE
Feature request: See notifications in the app as well

### ISSUE THREAD

**Issue by jeroenjacobs1205** [home-assistant/home-assistant-iOS#88] opened 2018-03-03 22:00 UTC
Hi,

When you sent notifications to an iPhone, they appear on the home screen of the ios device. However, once you click on them, it opens the HA app itself and the notifications are not visible there.

Please create a notifications area in the ios app, where you can recheck your notifications.

**Comment by mnoorenberghe** [comment] 2018-03-03 22:35
This is a duplicate of #49

**Closed by mnoorenberghe** 2018-03-03 22:35 UTC
