### ISSUE TITLE
Add toggles on-device for enabling each sensor

### ISSUE THREAD

**Issue by Joshfindit** [home-assistant/home-assistant-iOS#384] opened 2019-05-25 14:09 UTC
I'm not actually all that keen on tracking battery percentage or charging status on my iPad.

I'd prefer a menu in the Home Assistant app like:
```
Device sensors >
  - Battery state
  - Battery level
  - Location
  - SSID
  - SIM
  - Etc
```
Where each one is a switch-toggle (or a menu itself with switch-toggles, whatever else makes sense)

I know these sensors can be ignored in homeassistant, but I'd much rather turn off the tap than plug it if that makes sense.

**Comment by AlecRust** [comment] 2019-06-12 19:08
Dupe of https://github.com/home-assistant/home-assistant-iOS/issues/358.

**Comment by robbiet480** [comment] 2019-06-18 04:56
Closing as dupe

**Closed by robbiet480** 2019-06-18 04:56 UTC
Labels: 2.0 Beta, duplicate, feature-request
