### ISSUE TITLE
Upgraded to Home Assistant 0.100.1 and Companion app 2.0.0 Beta no longer loading

### ISSUE THREAD

**Issue by tkhan456** [home-assistant/home-assistant-iOS#445] opened 2019-10-11 07:05 UTC
Companion app 2.0.0 will crash  on my iPhone 11 Pro when it is launched after upgrading home assistant to 0.100.1. Wife' iPhone X works fine still.  I deleted the app and now it won't even complete the initial setup.  I can authenticate, give it location, motion and notification permission, but when it goes to make the integration with my home assistant server, it crashes every time at the pictured screen below.  I tried even setting it up on my iPad and it crashes at the same place. Occasionally getting Error Code 405 on the iPad but haven't seen that on the phone.
![IMG_717623D42F6F-1 2](https://user-images.githubusercontent.com/54510906/66631297-8132f680-ebcb-11e9-86b2-f28aa1b6829f.jpeg)

**Comment by TomBrien** [comment] 2019-10-11 07:15
This is a known bug and a fix is being worked on urgently.

**Comment by tkhan456** [comment] 2019-10-11 07:19
Great to hear.  Thanks for all the hard work everyone is doing.  I wish I knew more so I could contribute myself.

**Comment by TomBrien** [comment] 2019-10-11 07:35
I should mention that the release version seems unaffected.

**Comment by strfn** [comment] 2019-10-13 09:17
Same here

**Comment by tkhan456** [comment] 2019-10-14 03:00
Anyone know if the new Home Assistant 0.100.2 has fixed this issue or is this more an issue with the companion app?

**Comment by michalzadkowski** [comment] 2019-10-14 05:52
> Anyone know if the new Home Assistant 0.100.2 has fixed this issue or is this more an issue with the companion app?

Nope - the problem persists in 0.100.2

**Comment by ntompson** [comment] 2019-10-14 19:57
Same problem here - all broken now. @TomBrien you noted that the release version is still ok - do you mean the old clunker or that there is a release version of the 2.0.0 app?

**Comment by tkhan456** [comment] 2019-10-14 19:59
I don’t know if a release 2.0.0 version. I think the old companion app version. You can also downgrade to 0.99.3 of home assistant.  That seems to still work

**Comment by TomBrien** [comment] 2019-10-14 20:30
Sorry no I meant 1.5 which is the App Store version. Not sure I would call it clunky 😉

**Comment by ntompson** [comment] 2019-10-14 21:44
> I don’t know if a release 2.0.0 version. I think the old companion app version. You can also downgrade to 0.99.3 of home assistant. That seems to still work

Confirming that a downgrade to 0.99.3 worked for me. Perhaps a note should be attached to the 0.100.x releases to say that 2.0.0 iOS companion users should hold off on upgrade until this issue is resolved.

**Comment by SeanPM5** [comment] 2019-10-14 21:53
The problem is with a certain library in the 2.0 beta app that expects double digit version numbers. Now that Home Assistant has a triple digit version number (.100) that library is choking and crashing the entire app. Will require a new build of the app to be fixed.

Until a fix is released, you have three options at the moment:

1. Use the current stable App Store version (1.5.1) temporarily, which doesn't have this problem.
2. Downgrade Home Assistant to version 0.99.3. Here is the ssh command for Hass.io users: 
`hassio homeassistant update --version=0.99.3`
3. Use the [temporary workaround here](https://community.home-assistant.io/t/2-0-release-update/122298/194?u=seanm) that will allow you to be on the latest version of HA but "spoof" the version number to the app and thus avoid this crashing issue.

**Comment by tkhan456** [comment] 2019-10-18 03:11
New release. Reportedly has fixed it but in to worried to try the upgrade haha

**Comment by ntompson** [comment] 2019-10-18 03:12
Just applied build 66 through TestFlight and I'm getting HA API not configured in a red bar at the top of the screen. :-(

**Comment by SeanPM5** [comment] 2019-10-18 03:26
Message from Robbie:
>I was cleaning up code to do clean commits for these fixes and forgot to re-apply the 0.100 fix
>build 67 is building now

Build 66 does fix the Siri issue, image attachments in notifications, and a bunch of other things. The crash fix will be out in b67 soon.

**Comment by ntompson** [comment] 2019-10-18 04:39
Sorry for the truly stupid and off-topic question, but is there a way I can see the build 66 / build 67 etc commits / changes etc on GitHub?

**Comment by darkkatarsis** [comment] 2019-10-18 05:22
After today update there is still problem with app. Now its "HA API Manager that is unavailable"

**Comment by d0ugal** [comment] 2019-10-18 06:44
@ntompson you should be able to see it in one of the branches but there are no recent changes... so I’m unsure where the code is 🤷‍♂️ 

https://github.com/home-assistant/home-assistant-iOS/branches

**Comment by d0ugal** [comment] 2019-10-18 07:36
Build 67 is working well for me.

**Comment by jorisrymenants** [comment] 2019-10-18 07:37
> HA API Manager that is unavailable

I had the same problem, external URL was missing. I could not enter the correct external URL. So I deleted and reinstalled to retrigger onboarding process. But now I am experiencing issue #451 and can not login either

**Comment by mcchots** [comment] 2019-10-18 08:33
Fixed for me now in build 68

**Comment by TomBrien** [comment] 2019-10-18 11:16
Build 68, should fix this. You may need to delete the "Mobile App" integration (Configuration>Integrations) in HA then uninstall the app on you phone before reinstalling. Closing this for now. Feel free to reply on here if problem persists and we can re open.

**Closed by TomBrien** 2019-10-18 11:16 UTC
Labels: 2.0 Beta, bug

**Comment by ntompson** [comment] 2019-10-18 22:39
Confirming build 68 works for me. Following the "scorched earth" procedure seems to help with a clean reinstall (https://companion.home-assistant.io/en/next/troubleshooting/beta-cleaning).

@d0ugal - yes, that's as far as I got as well. Could it be that commits for the more recent builds are not being pushed back to GitHub??

**Comment by d0ugal** [comment] 2019-10-19 07:38
@ntompson unfortunately that seems likely
