### ISSUE TITLE
No sound and vibration on notification

### ISSUE THREAD

**Issue by mLupine** [home-assistant/home-assistant-iOS#377] opened 2019-05-17 17:18 UTC
Despite notification sounds being enabled in iOS settings, notifications received on the latest 2.0 Beta version of Home Assistant don't make any sound and don't vibrate, neither on the phone nor on the Apple Watch.

The same notifications sent to devices with the stable 1.5 version of the app work correctly – vibrate and play a sound.

**Comment by TomBrien** [comment] 2019-05-17 18:05
This is by design. Please see the [docs here](https://companion.home-assistant.io/en/next/notifications/basic#notification-sounds). I'm going to close this for now. If you continue to have issues, please reopen this issue

**Closed by TomBrien** 2019-05-17 18:05 UTC

**Comment by krissen** [comment] 2019-05-20 19:15
Not only is sounds off by default, but even when I specify a sound, like in the docs referenced, no sound is played.

Also (don't know if this would qualify as a separate bug or not, but) there should be vibration on the Apple Watch app, when a notification is received. (This would be the expected behaviour.) There is not. If there's a way to specify that there should be vibration / haptic feedback, great; let's add that to the docs!

**Comment by krissen** [comment] 2019-05-21 06:59
Nevermind. Was a typo in the docs. Works as intended. Jotting down the below in case it helps someone else.

To _test_, open up the services tab, choose `notify.mobile_app_myfancydevice` and call it with something like the following data:
```
{ "message": "test",
"data": { "push": { "sound": "default" } } }
```

Works. (Watch vibrates. Or phone chimes, if it's open.)

Also see "Notification sounds" in the new [documentation](https://companion.home-assistant.io/en/next/notifications/basic).
