### ISSUE TITLE
App loses enabled component state / connection with HA

### ISSUE THREAD

**Issue by markgoodyear** [home-assistant/home-assistant-iOS#31] opened 2017-04-27 20:01 UTC
I'm finding that at some point the app thinks that the components are no longer loaded / loses connection with HA, therefore location updates and notifications stop working. I can re-save under the "Connection" section and the components become re-enabled again. This can happen multiple times a day, and appear to be after I arrive at one of my locations/zones, but not 100% sure of that just yet. Once I re-save, location and notifications seem to work fine again.

I'm using 1.0.4 of the app along with 0.43.1 of HA, using Haasbian with letsencrypt and duckdns.

Screenshot of the components I'm meaning: http://d.pr/i/DyMvt/2xF7TMN4.

Does anyone have any ideas?

**Comment by cmsimike** [comment] 2017-04-27 20:12
I have been struggling with this too. I can't figure out why it disconnects me but I feel like it has been better after I messed with it a bit. There is definitely some weirdness with the connection timing out or otherwise dropping for some reason.

**Comment by hwikene** [comment] 2017-04-27 21:14
I`m using 1.0.4 app and 0.43.1 HA. I have the same issue. When i completley close app using home button. all three comonents turns off. When i press save. they start.

**Comment by B3voholic** [comment] 2017-04-27 22:09
I am also having this issue running 1.0.4 app version and 0.43.1 HA.  As soon as I press Save under connection, they become checked again.

**Comment by cmsimike** [comment] 2017-04-27 22:58
Nice debugging. That was exactly it for me - closing out of the app completely and going back in starts in a disconnected state. I can repeat it no problem

**Comment by markgoodyear** [comment] 2017-04-28 13:28
I can confirm that when I completely close the app it loses connection. However I can only seem to get this to happen when I'm not connected to WiFi. I still get this behaviour without closing the app though, this is what I've observe happened:

- Checked the app on 3G connection, and had no components enabled. Enabled them. Did **_not_** close the app, just let it go into the background.
- Entered my home location, WiFi connected, checked the app and all components were not enabled.

**Comment by markgoodyear** [comment] 2017-04-28 23:55
Adding a little more behaviour that I've noticed; I had the app with all components enabled whilst on WiFi, then let the app sit in the background. A few hours later, I checked the app and it had lost the components. The iPhone was in the same zone during that time, so it looks like it could be to do with the app losing connection when WiFi/network state changes. I believe WiFi gets disabled sometime after the phone gets locked, which would have been the cause in this situation.

**Comment by cmsimike** [comment] 2017-05-10 17:09
I have hass exposed directly on the internet, so dropping  off wifi shouldn't be an issue for the loaded components, however I am still seeing the ios app lose the components after some time in the background even with 100% connectivity to hass

**Comment by cmsimike** [comment] 2017-05-25 22:25
I feel like this issue has been getting worse for me. What used to be fairly consistent connectivity now drops out everyday

**Comment by markgoodyear** [comment] 2017-05-25 22:37
@cmsimike, I've had some hit and miss with this. Sometimes the app sends me the location change notifications, then it stops working. Then it can, without seemingly doing anything, randomly send me them again. I have an automation which sends a message when leaving home, this seems to fire more than via the app notifications for enter/exit though, and the HA dashboard generally has the location right, there is the odd occasion where it doesn't update.

**Comment by justinrhodes** [comment] 2017-06-03 16:07
@markgoodyear That is exactly what I experience with dropping the components and missing the location notifications.

**Comment by binbin2000** [comment] 2017-06-23 23:33
I can confirm that I have the exact same issues as well. Going from wifi to cellular disconnects the components, however it doesn't happen all the time. The app stays connected most of the time, but it's not 100% reliable, which is a requirement for me if it's going to be used for location updates.

**Comment by Uksa007** [comment] 2017-10-01 08:01
I have the exact same issues, app randomly disconnects, even when the phone is constantly connect to 4G. Three months an no updates, what's everyone using for reliable location updates opentracks?
I'm using 1.0.4 of the app along with 0.54.0 of HA on iphone 5s and 7 both IOS version 10.3.3 no SSL just standard http on port 8123.
Anyone tested with IOS11?

**Comment by cmsimike** [comment] 2017-10-02 15:12
FWIW even with this issue, I still find iOS tracking component much more accurate without ibeacons than Owntracks is with iBeacons.

**Comment by Uksa007** [comment] 2017-10-03 05:37
I find the opposite: 
Owntracks seems to pretty good at tracking when you set up a home region and share it with HA. 
Home Assistant iOS app, pretty much always fails to update when I leave and return, because it has lost connection with the HA server. It fails 100% of the time when have I WiFi on and it swaps from my home Wifi to 3G.

I'm not using ibeacons, just the phone with GPS.

**Comment by travislreno** [comment] 2017-11-20 02:55
Another report of this problem.  This breaks basic functionality of the app.  Once disconnected, the app will not report location until connection is manually re-estalished.

**Comment by cmsimike** [comment] 2017-11-21 02:18
I am still getting randomly disconnected as well.

**Comment by DanielGilbert** [comment] 2017-12-19 11:57
I'd like to chime in here. I'm neither a Swift developer, nor an iOS developer. I experience the same issue, and started looking at the code.

Basically, there are two points where the "components" list gets propagated: When the "WebView" gets created, and when you press "save" in the settings. After that, when accessing the "is xyz loaded" properties, the API can determine the correct settings.
I guess it's safe to assume that the "WebView" will always be loaded during runtime? If not, that might be the problem here.

The API itself is a singleton, afaik. What I'm wondering: What happens if the App is put to sleep, and only wakes up for the location update?

And another idea: would it make sense to propagate the "components" list also in "Setup()" method?

Would be cool if @robbiet480 could have a look at it some time. I don't have a dev environment for the apple universe, otherwise I would start debugging...

Happy holidays!

**Comment by RockNRollGeek** [comment] 2018-03-21 02:11
11 months and this still seems to be an issue, does anyone know if this is being worked on or what its progress might be?

**Comment by mderrick** [comment] 2018-06-18 15:13
I am still getting this issue and it makes device tracking useless. Is there any update or more information on this?

**Comment by DanielGilbert** [comment] 2018-06-18 15:58
Looks like this Pull-Request might fix this issue:

https://github.com/home-assistant/home-assistant-iOS/pull/101

Hopefully, this update will be pushed to the App Store. :)

**Comment by digidestination** [comment] 2018-11-26 08:40
Hi, I still have this issue, it does happen every so often. My hasio is on http and not on https, could that be the reason?

**Comment by DanielGilbert** [comment] 2018-11-26 15:47
> Hi, I still have this issue, it does happen every so often. My hasio is on http and not on https, could that be the reason?

Certainly not - looks like the long awaited update is still pending. App Store still shows 1.1.1 for me.

**Comment by robbiet480** [comment] 2019-02-23 09:07
Assuming this is no longer an issue since 1.5.0 came out. Please let me know if that's incorrect and i'll reopen.

**Closed by robbiet480** 2019-02-23 09:07 UTC
Labels: bug
