### ISSUE TITLE
Full screen

### ISSUE THREAD

**Issue by 0x00-0xFF** [home-assistant/home-assistant-iOS#436] opened 2019-09-13 11:44 UTC
I would like to have the companion app full screen so I can take the full advantage of the size of my ipad/homeassistant.

**Comment by SeanPM5** [comment] 2019-09-13 14:52
Not sure which version of the HA iOS app you are using, but the [public beta version](https://testflight.apple.com/join/TUL8eu8N) got rid of the bottom toolbar area.

With [Compact Custom Header](https://github.com/maykar/compact-custom-header) you can minimize or completely hide the top "header" area too. It offers a lot of customization options to get it just the way you want it.

And if you visit your profile page in Home Assistant (your initials in bottom of sidebar) from your iPad, you can turn on the option "Always hide the sidebar". It is a device specific setting.

With the combination of those three things you can achieve what you're after. Hope this helps.

**Comment by 0x00-0xFF** [comment] 2019-09-13 15:20
Besides that's awesome, I ment fullscreen... like hiding the clock/wifi/etc.

**Comment by TomBrien** [comment] 2019-10-14 20:44
This is a duplicate of #405. Closing this in favour of the original issue

**Closed by TomBrien** 2019-10-14 20:44 UTC
Labels: duplicate
