### ISSUE TITLE
Network is always unknown 

### ISSUE THREAD

**Issue by Unthred** [home-assistant/home-assistant-iOS#446] opened 2019-10-11 18:06 UTC
Home Assistant 0.99.0.
Ios app version: 1.5.0 (21)

On the ios app current network name is always “unknown”, even on wifi and the internal url does not work anymore. I am not sure when this started as it used to work fine. 
I have a reverse proxy running and an internal dns server, my router allows me to set dns host names which I have. So no matter what address I use be it a web browser on a pc or my android phone or tablet I can use the same external url and it redirected to the right internal ip address when your connected to my home wifi. 

With the ios app I cannot use the external url whilst connected to my home network and I cannot connect using the internal one so my gf has to disconnect her wifi whenever she wants to use it.

I really dont understand how or why this is happening.

Any suggestions to troubleshoot

Thanks

**Comment by TomBrien** [comment] 2019-10-11 18:19
The app is basically a web browser window so this is rather odd. Is your external address `http` or `https`? Have you tried resetting the app up?

**Comment by Unthred** [comment] 2019-10-11 18:41
Agreed I don't understand it. access is https. I have tried uninstalling and reinstalling the app.
I dont use ios itsd my girlfriend phone so I dont know much about it. Does uninstalling it completely wipe the settings or should I do something else?

I have checked the ip address and dns settings on the phone and it all seems to be correct. From what you just said I will try and access it via safari and see if that works.

Thanks for the prompt response!

**Comment by Unthred** [comment] 2019-10-11 19:14
So my gf just got home and I have tried safari and chrome and neither of them can connect to HA
Safari reports
The error was: "FetchEvent.respondWith received and error: no-response: no-response :: [{"url":"https://home.mydomain.com/", "error":{}}]"

Don't suppose this means anything to you?

**Comment by TomBrien** [comment] 2019-10-11 20:17
Im almost certain this has to be something weird with the reverse proxy. I’ve asked someone from the Discord channel to pop over when he has a chance. But out of my zone of knowledge. Do you have an entry like the following in your `configuration.yaml` (note no protocol or port)?

``` yaml
http:
  base_url: home.mydomain.com
```

**Comment by TomBrien** [comment] 2019-10-11 20:19
I’m almost certain this has to be something weird with the reverse proxy. I’ve asked someone from the Discord channel to pop over when he has a chance. But out of my zone of knowledge. Do you have an entry like the following in your `configuration.yaml` (note no protocol or port)?

``` yaml
http:
  base_url: home.mydomain.com
```

**Comment by olbjan** [comment] 2019-10-12 07:14
Hi,

dropping in as asked ;-)
We may be looking at multiple things here from what I'm reading. First on the iOS network "unknown" issue, I believe this could be caused by the iOS 13 update which might have reset app permissions. I believe the app needs permission to access location data to get the SSID info from the OS. I've seen this permission be reset during the iOS 13 beta phase and it needed to be manually restored.
So please check iOS settings -> Home Assistant -> Location -> and ensure the app is given a higher permission level than "never"; if you use the location tracking feature of the app, set permission to "always".

Second you may want to update the app to at least 1.5.1 as version 1.5.0 has been out of date for quite a while.

Now, I do not believe this will solve anything for your connectivity problem as none of this would impact Safari on iOS. I believe the issue is likely to be DNS though. As you said that you are able to access HA from other devices via your internal DNS, I suspect something on the iOS device has messed with DNS settings.

Please check on the Phone in iOS settings -> Wifi -> Your network whether a manual DNS server has been set and whether the phone maybe has been assigned an IPv6 DNS server that is resolving to your external IP. I think it is quite likely that the OS may be sending its name resolution queries to a different name server than your router. You can try setting your router as the only manual DNS server.

If this is not the solution it may be around what Tom suggested and you can check your auth and reverse proxy settings:

Please check that in your configuration.yaml the http: section has something like this:
```
http:
  # Add use_x_forwarded_for because of NGINX reverse proxy
  use_x_forwarded_for: true
  # Add trusted_proxies because of NGINX reverse proxy, use Docker subnet
  trusted_proxies: 
    - 172.30.32.0/23 # This is the docker subnet when hass.io NGINX addon is used
    - 127.0.0.1
    - ::1
    # You may need to add the full IPv6 address of your Reverse Proxy if your network is IPv6 enabled
  base_url: http://office.b4value.net
```

**Comment by TomBrien** [comment] 2019-10-14 20:31
@Unthred have you managed to resolve this?

**Comment by Unthred** [comment] 2019-10-15 06:17
Sorry I have been super busy recently and have only noticed these replies just now. I will try out these solutions tonight when I get home.

thanks very much for the responses. I will report back later

**Comment by Unthred** [comment] 2019-10-16 20:52
Hey Guys,
    So I have tried your suggestions with no success I am afraid.  The Location setting was already higher than never, I set it to always just incase. The automatic DNS settings all seem fine to me but just to be sure I changed it to manual and entered them myself..... no difference. The only part that I think is to do with the IOS app is the network name unknown, the rest of it must be the iphone is not playing nice with my DNS server / edgerouter.

Some more info to see if it helps
The IOS app was already at 1.5.1. 
I have forgotten and rejoined the network with no effect.
My home network does not have ipv6 enabled
When connected to the internal network I cannot access my external url for home assistant
I have a linux desktop, windows 10 laptop, android tablet and phone all of which have no issues at all.

Got it Working!!!! I am not happy with how but it works. So I set all networking to manual entered a different ip address, set the subnet and gateway then set the DNS server to manual and entered that too. I now have internal name resolution and I can just keep using the external url for home assistant it when inside it will translate to the internal ip.

I have no idea why the iphone is behaving like this but I can just leave it all manual and stick a dhcp exception so that the iphones ip address is never given out to any other device. 

Still have network unknown but its not causing me an issue. 

I am happy to try and help you debug and fix the issue though, but its not a priority at all.

Thanks again for all your replies.

**Comment by TomBrien** [comment] 2019-10-22 20:16
Closing for now but let us know if your solution stops working

**Closed by TomBrien** 2019-10-22 20:16 UTC
Labels: 1.5.x
