### ISSUE TITLE
Location Settings - zones with apostrophes show a blank space

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/home-assistant-iOS#308] opened 2019-05-02 02:50 UTC
Minor thing. In 2.0b any apostrophes for zones don't show in Location Settings, and it leaves an empty space.
 
![Zone](https://user-images.githubusercontent.com/9065557/57053144-2da2a100-6c5a-11e9-8b37-d988389a14c7.jpg)

I just checked 1.5.1 and the apostrophes were also stripped out there, but it didn't leave the empty blank space. It would just say "MEGANS" rather than "MEGAN S" for example which is more visually appealing.

**Comment by SeanPM5** [comment] 2019-05-30 06:22
Small update to this, issue also appears in the actual zone notification too (which I didn't have enabled before so never noticed). It looks even more awkward here since the zone name is normal case and the S is uppercase.

![IMG_0280](https://user-images.githubusercontent.com/9065557/58612284-01416b00-8280-11e9-88f2-4a4dc1d2d11d.jpg)

No big deal, just wanted to make a note that it's not just limited to this location settings page.

**Comment by robbiet480** [comment] 2019-06-18 06:22
Fixed by importing zone's `friendly_name` instead of making our own name by replacing characters (we still do that but only as a fallback).

**Closed by robbiet480** 2019-06-18 06:22 UTC
Labels: 2.0 Beta, location

**Comment by sphanley** [comment] 2021-01-26 05:28
This seems to be occuring still (or again?). Should I submit a new issue? Not sure if the issue is with the iOS app, or whether it's something quirky about the way the `friendly_name` is processed for zones on the Core side.
