### ISSUE TITLE
Mobile device sensor entity IDs

### ISSUE THREAD

**Issue by ipodmusicman** [home-assistant/home-assistant-iOS#418] opened 2019-07-13 06:03 UTC
I've been using the 2.0.0 (62) beta for some time now and I noticed all the new sensors that appeared in HA based on the phone's sensors like geolocation, steps, activity, etc.  I noticed that these sensor entity IDs are named without having the device's name into consideration.  At the moment, my phone has beta 2.0.0 loaded, but my wife is still using v1.5 of the iOS app.

Once the app is officially released, what would happen once the app running on my wife's phone starts to publish sensor data?  Wouldn't it be better to name these sensors based on the name of the device thus when a new mobile phone is added, the sensors will be named uniquely?

I'm using iOS 12.3.1

**Comment by SeanPM5** [comment] 2019-07-13 06:44
This is on the roadmap, but it's probably unlikely to make the initial 2.0 release at this point.

When your wife installs it on her phone, it will create the same sensors but with a _2 at the end. So yours will be `sensor.battery_state` and hers will be `sensor.battery_state_2` for example. So despite the ugliness, the entity id's will still be "unique" and there won't be any data conflicts.

However, you can head to the Configuration -> Integrations page, click on the Mobile App section for your phone(s) and manually add the device name prefix you want to all the sensors. You will have to rename each sensor one-by-one for now, which is not ideal, but it shouldn't take more than a couple minutes.

**Comment by ipodmusicman** [comment] 2019-07-13 07:11
Thanks for your response and glad it is part of the roadmap.  I figured that this would be the interim solution for now.  I'll rename all the entity IDs in anticipation.

**Comment by TomBrien** [comment] 2019-12-01 22:49
This is a duplicate of (the albeit more recent) #478. As that relates to the release version I’ll close this as the duplicate (little backwards I know)

**Closed by TomBrien** 2019-12-01 22:49 UTC
