### ISSUE TITLE
Location not updating automatically, only manually

### ISSUE THREAD

**Issue by Vinz87** [home-assistant/home-assistant-iOS#449] opened 2019-10-15 10:28 UTC
Location never gets automatically updated. If I click on the manual update location icon, it correctly gets updated and the device tracker assumes the correct state based on the zone I'm in.

iOS app v1.5.1
Home Assistant v0.100.1

**Comment by TomBrien** [comment] 2019-10-16 06:03
Can you check in the iOS settings under Privacy then Location Services that Home Assistant has permission set to Always and not While Using

**Comment by Vinz87** [comment] 2019-10-18 20:50
After

**Comment by Vinz87** [comment] 2019-10-18 20:51
After several days of testing I can say that location updating works as expected only if the app is carefully kept opened in background.

**Comment by TomBrien** [comment] 2019-10-19 11:37
Did you check the location permissions? I cannot reproduce this on a device running iOS 13 and HA Companion 1.5.1

**Comment by olbjan** [comment] 2019-10-21 07:29
I can't repro this either. Trackers based on 1.5.1 on both my phone and my wife's all work as expected... which is to say not great.

Some background: The apps only update location (in the background) based on what Apple calls a "Significant location change" and only when the location fix is better than a 1000m radius. What this means is that basically, the app will be triggered from iOS when the iPhone is moving between cell towers. Unfortunately unless you are running a navigation app (say Apple or Google maps) at the time, the iPhone will not have a good location fix based just on cell tower data, especially if you are in a moving vehicle. Thus location fixes often end being greater than 1000m accurate and won't be reported to Home Assistant.
You can see this in the application log.

What does work better are geofencing areas (zones in Home Assistant) where the app basically tells iOS which areas to look out for to be woken and report location. This works quite well when your zones are not too close to each other.

If you want pretty much instantaneous zone entries you will have to resort to something like iBeacons. Those work great for immediate and reliable zone entry notifications but are not that great when it comes to exits.

In the end gps based device tracking is a trade-off between saving battery and accuracy. For purposes of using automations with home assistant, the current setup works well enough.

**Comment by robbiet480** [comment] 2019-11-26 15:45
Closing this as its a 1.5.x issue and 2019.1/2.0 has just been released. Please re-open this issue if this action was incorrect. Thanks!

**Closed by robbiet480** 2019-11-26 15:45 UTC
Labels: 1.5.x
