### ISSUE TITLE
Missing support for apns del-id

### ISSUE THREAD

**Issue by olbjan** [home-assistant/home-assistant-iOS#419] opened 2019-07-15 10:37 UTC
With 2.0 there is now support for apns-collapse-id to replace notifications but there is no support to delete a notification.

This same functionality exists for the HTML5 push notifications framework and should be possible to implement:
https://medium.com/@sebastianosiski/implementing-removable-remote-notifications-on-ios-a17d74832bde

**Comment by non092** [comment] 2019-07-24 15:56
Would be useful to be able to delete notification
In my setup im sending notifications to multiple phones and it would be great to be able to delete it once it has been actioned on one phone

**Comment by TomBrien** [comment] 2019-10-19 14:19
This is a duplicate of #258 closing in favour of the original

**Closed by TomBrien** 2019-10-19 14:19 UTC
Labels: duplicate
